// Generated by CoffeeScript 1.10.0
(function() {
  var getFace, run;

  getFace = function() {
    var HOUR, MINUTE, face, fiveFMT, fmtFace, fmtFaceLines, hour, hourFMT, i, j, k, l, len, len1, len2, len3, len4, m, mi, minFMT, ref, ref1, ref2, ref3, ref4, t;
    face = '[I T \' S] X [A B O U T] E\n[A] C [Q U A R T E R] D C\n[T W E N T Y] [F I V E] X\n[H A L F] B [T E N] F [T O]\n[P A S T] E R U [N I N E]\n[O N E] [S I X] [T H R E E]\n[F O U R] [*F I V E*] [T W O]\n[E I G H T] [E L E V E N]\n[S E V E N] [T W E L V E]\n[T E N] S E [O C L O C K]';
    t = new Date();
    HOUR = t.getHours() % 12 || 12;
    MINUTE = t.getMinutes();
    fmtFace = function(match, val, repl) {
      var fmt_on, src;
      if (repl == null) {
        repl = true;
      }
      src = "[" + val + "]";
      fmt_on = "<span class='light'>" + val + "</span>";
      if (match) {
        return face = face.replace(src, fmt_on);
      } else if (repl) {
        return face = face.replace(src, val);
      }
    };
    minFMT = function(items) {
      var match, nMinFrom, nMinTo, repl, val;
      nMinFrom = items[0], nMinTo = items[1], val = items[2], repl = items[3];
      match = ((nMinFrom <= MINUTE && MINUTE < nMinTo)) || (nMinFrom === -1);
      return fmtFace(match, val, repl);
    };
    hourFMT = function(items) {
      var match, nHour, repl, val;
      nHour = items[0], val = items[1], repl = items[2];
      match = (nHour === HOUR) || (nHour === 0);
      return fmtFace(match, val, repl);
    };
    fmtFaceLines = function() {
      var i, index, len, lines, value;
      lines = face.split('\n');
      for (index = i = 0, len = lines.length; i < len; index = ++i) {
        value = lines[index];
        lines[index] = "<div class='row'>" + value + "</div>";
      }
      return face = lines.join('\n');
    };
    fiveFMT = function() {
      return face = face.replace('*', '').replace('*', '');
    };
    minFMT([-1, -1, "I T ' S"]);
    minFMT([-1, -1, 'A B O U T']);
    if (MINUTE < 35) {
      ref = [[15, 20, 'A'], [15, 20, 'Q U A R T E R'], [20, 30, 'T W E N T Y'], [25, 30, 'F I V E', false], [5, 10, 'F I V E'], [10, 15, 'T E N']];
      for (i = 0, len = ref.length; i < len; i++) {
        mi = ref[i];
        minFMT(mi);
      }
      ref1 = [[9, 'N I N E'], [1, 'O N E'], [6, 'S I X'], [3, 'T H R E E'], [4, 'F O U R'], [5, '*F I V E*'], [2, 'T W O'], [8, 'E I G H T'], [11, 'E L E V E N'], [7, 'S E V E N'], [12, 'T W E L V E'], [10, 'T E N']];
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        hour = ref1[j];
        hourFMT(hour);
      }
    } else {
      ref2 = [[45, 50, 'A'], [45, 50, 'Q U A R T E R'], [35, 45, 'T W E N T Y'], [35, 40, 'F I V E', false], [55, 61, 'F I V E'], [50, 55, 'T E N']];
      for (k = 0, len2 = ref2.length; k < len2; k++) {
        mi = ref2[k];
        minFMT(mi);
      }
      ref3 = [[8, 'N I N E'], [12, 'O N E'], [5, 'S I X'], [2, 'T H R E E'], [3, 'F O U R'], [4, '*F I V E*'], [1, 'T W O'], [7, 'E I G H T'], [10, 'E L E V E N'], [6, 'S E V E N'], [11, 'T W E L V E'], [9, 'T E N']];
      for (l = 0, len3 = ref3.length; l < len3; l++) {
        hour = ref3[l];
        hourFMT(hour);
      }
    }
    ref4 = [[0, 5, 'O C L O C K'], [5, 35, 'P A S T'], [30, 35, 'H A L F'], [35, 61, 'T O']];
    for (m = 0, len4 = ref4.length; m < len4; m++) {
      mi = ref4[m];
      minFMT(mi);
    }
    fiveFMT();
    fmtFaceLines();
    return face;
  };

  run = function() {
    var clock;
    clock = document.getElementById('clock');
    clock.innerHTML = getFace();
    return setTimeout(run, 15000);
  };

  window.onload = function() {
    return run();
  };

}).call(this);
